---
kind: pipeline
name: build

steps:
  - name: build
    image: golang:1.7
    environment:
      USERNAME:
        from_secret: username
    commands:
      - go get
      - go build
      - go test
      - echo $USERNAME > a.txt
      - cat a.txt 