---

- hosts: all
  gather_facts: no

  tasks:
    - name: ADD a new Tenant
      cisco.aci.aci_tenant:
        hostname: '{{ inventory_hostname }}'
        validate_certs: no
        tenant: TN_ansible_test
        state: present
      delegate_to: localhost
