---

- hosts: all
  gather_facts: no

  tasks:
    - name: Add a new AP
      cisco.aci.aci_ap:
        hostname: '{{ inventory_hostname }}'
        validate_certs: no
        tenant: tn_ansible_awx_test
        ap: anp_ansible_awx_test
        state: present
      delegate_to: localhost
