---

- hosts: all
  gather_facts: no

  tasks:
    # task 1
    - name: ADD a new BD
      cisco.aci.aci_bd:
        hostname: '{{ inventory_hostname }}'
        validate_certs: no
        tenant: tn_ansible_awx_test
        bd: bd_178-178-178-000
        vrf: vrf_ansible_awx_test
        state: present
      delegate_to: localhost

    # task 2
    - name: ADD a new BD subnet
      cisco.aci.aci_bd_subnet:
        hostname: '{{ inventory_hostname }}'
        validate_certs: no
        tenant: tn_ansible_awx_test
        bd: bd_178-178-178-000
        gateway: 178.178.178.178
        mask: 24
        state: present
      delegate_to: localhost
