---
- hosts: ALL
  tasks:
    # task 1
    - name: cat /etc/passwd
      command: cat passwd
      args:
        chdir: /etc
      register: message

    # task 2
    - name: print debug message
      debug:
        msg: "{{ message.stdout }}"
    - copy:
       content: "{{ message.stdout | replace('\\n', '\n') }}"
       dest: "/tmp/{{ inventory_hostname }}.show"