---
  
- hosts: localhost
  gather_facts: no

  tasks:
  -  name: FS usage
     shell: df -h {{ FS_MOUNTPOINT }} |awk ' { print $5 } ' |grep -v Use
     register: dffs

  -  debug:
       msg: "System {{ inventory_hostname }}'s {{ FS_MOUNTPOINT }} FS utiliation is {{ dffs.stdout }}"
