---

- name: Gathering Interface Info
  hosts: ctbcstaging
  connection: local
  gather_facts: false

  vars_files:
    - external_vars.yml

  tasks:
  - name: "1] API Query - All Interface Status"
    aci_rest:
      host:           "{{ aci_host }}"
      user:           "{{ aci_user }}"
      password:       "{{ aci_password }}"
      validate_certs: "{{ aci_valid_cert }}"
      use_ssl:        "{{ aci_use_ssl }}"
      path:           "/api/class/ethpmPhysIf.json"
      method:         "get"
    register: ethpmPhysIf

  - name: "2] export to JSON format"
    copy:
      content: "{{ ethpmPhysIf | to_nice_json }}"
      dest: ethpmPhysIf_full.json

  - name: "3] Query Specific info and export to JSON format"
    copy:
      content: "{{ ethpmPhysIf | json_query('
        imdata[].ethpmPhysIf.attributes.{
          dn:dn,
          operSt:operSt,
          operMode:opermode,
          operSpeed:operSpeed}') | to_nice_json }}"
      dest: ethpmPhysIf_custom.json